"""SynthesisAgent plus the code-side disagreement object. Refuses to run without both memos."""

from __future__ import annotations

from ..llm.openrouter import OpenRouterClient
from ..schemas import Band, Brief, Disagreement, EvidenceBundle, Lean, Memo, QuantResult, SynthesisOut
from ..tracing import Tracer
from .memo import label_claims
from .prompts import synthesis_messages


class PipelineOrderError(RuntimeError):
    pass


ALIGNED: dict[Band, set[Lean]] = {"attractive": {"bullish"}, "expensive": {"bearish"}, "fair": {"neutral", "mixed"}, "unknown": set()}


def build_disagreement(q: QuantResult, lean: Lean, quant_wrong: list[str], narrative_wrong: list[str]) -> Disagreement:
    agree = lean in ALIGNED[q.quant_band]
    if q.quant_band == "unknown":
        summary = "The quant score could not be computed (too little data), so there is nothing for the narrative to agree or disagree with. Treat the narrative as unanchored."
    elif agree:
        summary = f"Quant band '{q.quant_band}' and narrative lean '{lean}' point the same way. Agreement is not proof; both draw on overlapping data."
    else:
        summary = f"Quant says '{q.quant_band}' (score {q.quant_score}); the narrative leans '{lean}'. This is shown, not reconciled. One of them is wrong, or the horizon differs."
    qw = list(quant_wrong) or [f"{f}" for f in q.freshness_flags] or ["v0 formula uses fixed reference bands rather than sector peers"]
    nw = list(narrative_wrong) or ["Memos are generated by a small free model and may over-weight the most legible evidence"]
    return Disagreement(quant_band=q.quant_band, quant_score=q.quant_score, narrative_lean=lean, agree=agree, disagreement_summary=summary, quant_may_be_wrong_because=qw, narrative_may_be_wrong_because=nw)


def synthesise(b: EvidenceBundle, q: QuantResult, bull: Memo | None, bear: Memo | None, *, client: OpenRouterClient | None, model: str, thesis: str | None, horizon: str, tracer: Tracer | None = None) -> Brief:
    if bull is None or bear is None:
        raise PipelineOrderError("Synthesis requires both a bull memo and a bear memo as first-class artifacts")
    known = {s.source_id for s in b.sources}
    if client is None:
        lean: Lean = "mixed"
        dis = build_disagreement(q, lean, [], ["No LLM synthesis was run (stub); the narrative lean is a placeholder"])
        return Brief(ticker=b.ticker, one_view="[STUB — no OPENROUTER_API_KEY] Bull and bear memos were built from quant components only. The disagreement object below is computed by code against the quant band.", narrative_lean=lean, claims=[], kill_criteria=[f"Watch: {f}" for f in q.freshness_flags] or ["Set a key to get model-written kill criteria"], disagreement=dis, model=None, provider=None, is_stub=True)
    out, res = client.chat_json(synthesis_messages(b, q, bull, bear, thesis, horizon), SynthesisOut, model=model, tracer=tracer, name="synthesis")
    dis = build_disagreement(q, out.narrative_lean, out.quant_may_be_wrong_because, out.narrative_may_be_wrong_because)
    return Brief(ticker=b.ticker, one_view=out.one_view, narrative_lean=out.narrative_lean, claims=label_claims("syn", out.claims, known), kill_criteria=out.kill_criteria, disagreement=dis, model=res.model, provider=res.provider, is_stub=False)
